# Generated by Django 4.0.6 on 2022-08-31 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from coupon.gen_master_data import gen_master


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='쿠폰 이름')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='쿠폰 가격')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='쿠폰 퍼센트')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록 날짜')),
            ],
            options={
                'db_table': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='CouponUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='발급일')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coupon_user',
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ManyToManyField(related_name='coupon_user', through='coupon.CouponUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(gen_master),
    ]
