# Generated by Django 4.0.6 on 2022-08-16 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_real',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productreal'),
        ),
    ]
